### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by veimox** [ros-visualization/interactive_marker_twist_server#14]
I was wondering what are the release plans for melodic.

I have cloned the repo, compiled it and tested it without any problems in Ubuntu bionic.

**Comment by veimox** [comment]
up!

**Comment by wxmerkt** [comment]
We'd love to see this package released as well - and happy to volunteer to help out with maintenance/release.

**Comment by wxmerkt** [comment]
Happy to volunteer in maintenance and release - is there anything blocking a Melodic release right now?

**Comment by tonybaltovski** [comment]
Happy to volunteer as well.

**Comment by mikepurvis** [comment]
Done: https://github.com/ros/rosdistro/pull/21763

Sorry for the wait, everyone.
